name: CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.13' 
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Tests
        run: |
          pytest
      - name: Coverage Run
        run: |
          coverage run -m --omit=*test* pytest -v
      - name: Coverage Report
        run: |
          coverage report -m
